### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by SeanZhi** [ranafi/CYCLOPS#1]
Is there a new version of cyclops? Some functions not support in the new version of Julia.

**Comment by ranafi** [comment]
I have a version that runs of Juli 0.6 (the one online runs on 0.3)
I will share this with you (or anyone) on request

However there are many more changes since the rollout of Julia 1.x
We are presently working on a version for Julia 1 - with many changes

-ron

**Comment by SeanZhi** [comment]
Can you upload the new version of CYCLOPS ?

**Comment by ranafi** [comment]
Do you mean the version that runs on Julia O.6? We are not yet ready to
release a version for the newest version of Julia..

**Comment by SeanZhi** [comment]
Yeah, Julia 0.6. I want to test it.
