### ISSUE TITLE
About results

### ISSUE THREAD

**Issue by SeanZhi** [ranafi/CYCLOPS#3]
Hi 
  I try to test CYCLOPS  with my own data. After modified the script of "CYCLOPS_v6_2.0A_HumanLung_share.jl" (reset  N_best =40, total_background_num=200, path = my_local_path). I ran the program on my computer. But it's seem that i didn't get right results. The estimated phase list show that all the samples get a same phase except first one.
![image](https://user-images.githubusercontent.com/40906340/66697445-48e50280-ed08-11e9-9c38-61173af71b8f.png)
output of estimated phase list
What could be caused of this problem?

**Comment by ranafi** [comment]
Sorry - for the delayed response
(I have been a bit busy)

Did it work correctly with provided test data?

Perhaps I could help best if I new more about your data, seed genes, et
I realize you might not want to post this to Git

Please email me directly - I can try to take a look

-Ron

**Comment by SeanZhi** [comment]
Thanks for your reply.
 After restart the JunliaPro, The result seems to be a little different than before. I am not sure if the result is correct. But it works.
Some problems i will email you directly. If you have free time. Thanks

**Comment by gangwug** [comment]
This is closed. Please email the author if meeting an issue when running CYCLOPS.

**Comment by gangwug** [comment]
This is closed.

**Comment by gangwug** [comment]
This is closed.
