### ISSUE TITLE
Syntax error!

### ISSUE THREAD

**Issue by SeaBD** [ranafi/CYCLOPS#4]
Hello,

I am interested in applying CYCLOPS on my dataset, however, I keep receiving the following error when I try to load CYCLOPS_v6_2a_AutoEncoderModule.jl and CYCLOPS_v6_2a_AutoEncoderModule_multi.jl scripts:

LoadError: syntax: "module" at C:\My\Local\Path\to\CYCLOPS_v6_2a_AutoEncoderModule.jl:1 expected "end", got "Input_Layer"
Stacktrace:
  [1] top-level scope
    @ C:\My\Local\Path\to\CYCLOPS_v6_2a_AutoEncoderModule.jl:39
  [2] include(fname::String)
    @ Base.MainInclude .\client.jl:451
  [3] invokelatest(::Any, ::Any, ::Vararg{Any}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base .\essentials.jl:716
  [4] invokelatest(::Any, ::Any, ::Vararg{Any})
    @ Base .\essentials.jl:714
  [5] evaluate!(call::Main.RConnector.Call, communicator::Main.RConnector.CommunicatoR{Sockets.TCPSocket})
    @ Main.RConnector C:\Users\seabd4\AppData\Local\Programs\R\R-4.2.0\library\JuliaConnectoR\Julia\evaluating.jl:67
  [6] evaluate_checked!(call::Main.RConnector.Call, communicator::Main.RConnector.CommunicatoR{Sockets.TCPSocket})
    @ Main.RConnect

Therefore, I am not able to run the program on any dataset!

Would you please give me a hint on this issue? 

Thank you in advance.

**Comment by ranafi** [comment]
What is this about an RConnector call? Are you trying to run this through R
I have no idea about that

**Comment by SeaBD** [comment]
Thank you for your promt response.
Yes I was trying to run it through R, however, when I run it through Julia, the following error appears:

ERROR: LoadError: syntax: "module" at C:\Local\to\CYCLOPS_v6_2a_AutoEncoderModule.jl:1 expected "end", got "Input_Layer"
Stacktrace:
 [1] top-level scope
   @ C:\Local\to\CYCLOPS_v6_2a_AutoEncoderModule.jl:39
 [2] include(fname::String)
   @ Base.MainInclude .\client.jl:451
 [3] top-level scope
   @ REPL[2]:1
in expression starting at C:\Local\to\CYCLOPS_v6_2a_AutoEncoderModule.jl:39


Also, I would like to mention that CYCLOPS_v6_2a_CircularStats_U and CYCLOPS_v6_2a_Seed scripts successfully run on both Julia and R.

**Comment by ranafi** [comment]
What version of Julia?

**Comment by SeaBD** [comment]
I am using version 1.7.3 (2022-05-06)

**Comment by ranafi** [comment]
As I think the documentation says
The current posted version of Cyclops is for Julia 0.6x

There are comparability issues with newer versions.

I will be out for a few weeks. If you would like to discuss your intended
use case in more detail after my return..I would be happy to talk with you.

Please email me directly (contact info in Cyclops paper). I can also send
some files needed for test scripts..

**Comment by SeaBD** [comment]
I appreciate your considerations and your precious offer. 

For now, I will try Julia 0.6x if it does not work, I will contact you directly.

Best regards

**Comment by Sally-Zhang** [comment]
Hello, I have the same issue about this. 

> I appreciate your considerations and your precious offer.
> 
> For now, I will try Julia 0.6x if it does not work, I will contact you directly.
> 
> Best regards

Hello, I have the same issue about this. Does it work when you try Julia 0.6x?

**Comment by ranafi** [comment]
Yes it seems to work for others when they use Julia 0.6x
(Although one person emailed me with a recent, different installation
issue?)
Also the error message that was originally shown on this thread
referenced an R binding to Julia
I have not tried that - and I know it is not supported for Julia 0.6x
You will need to run it in Julia itself

As, I mentioned in the previous reply to this thread if you email me
directly (contact info in CYCLOPS paper)
I can provide additional test data files etc

**Comment by gangwug** [comment]
This is closed. Please email the author for details if meeting a similar issue.

**Comment by ranafi** [comment]
What version of Julia are you using?
